name: CI and coverage

on:
  push:
    branches:
      - 'v1.[0-9]+.[0-9]+'
      - 'dev'
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: avsm/setup-ocaml@master
      - name: Install OPAM deps
        run: opam install -y --deps-only --with-test .
      - name: Test build
        run: opam exec -- dune build .
      - name: Run tests
        run: opam exec -- dune runtest --instrument-with bisect_ppx --force
      - name: Send report
        run: opam exec -- bisect-ppx-report send-to Codecov
